# Generated by Django 5.0.6 on 2024-06-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0003_privatemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OffreVoyage',
        ),
    ]
