# Generated by Django 5.0.6 on 2024-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0004_delete_offrevoyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='numero_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offrecolis',
            name='numero_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
